'use strict';
const {Game,generals,roles,cards}=SGS;
const $=id=>document.getElementById(id);
let game,selected=new Set(),timer=null,epoch=0;
const missions={lord:'你是主公：与忠臣一起消灭反贼和内奸。',loyalist:'你是忠臣：保护主公，消灭反贼和内奸。',rebel:'你是反贼：击败主公，阻止内奸独胜。',renegade:'你是内奸：先除掉忠臣和反贼，最后击败主公。'};
function button(text,fn,parent){const b=document.createElement('button');b.textContent=text;b.onclick=()=>act(fn);parent.append(b);return b;}
function act(fn){try{fn();$('error').textContent='';render();schedule();}catch(e){$('error').textContent=e.message;}}
function reset(){clearTimeout(timer);epoch++;game=new Game();selected.clear();$('setup').hidden=false;$('battle').hidden=true;$('identity').textContent=`你的身份 · ${roles[game.players[0].role]}`;$('mission').textContent=missions[game.players[0].role];$('generals').replaceChildren();for(const g of generals){const b=button('',()=>{game.start(g.id);$('setup').hidden=true;$('battle').hidden=false;},$('generals'));b.className='general';b.innerHTML=`<small>${g.kingdom} · ${g.hp}体力</small><strong>${g.name}</strong><span>${g.skill}</span><p>${g.text}</p>`;b.setAttribute('aria-label',`选择${g.name}`);}}
function render(){if(game.phase==='identity')return;const me=game.players[0],current=game.players[game.turn];selected=new Set([...selected].filter(id=>me.hand.some(c=>c.uid===id)));$('status').textContent=`第 ${game.round} 回合 · ${game.name(current)} · ${{ready:'准备摸牌',play:'出牌阶段',discard:'弃牌阶段',over:'已结束'}[game.phase]}　｜　牌堆 ${game.deck.length} · 弃牌 ${game.discard.length}`;$('players').replaceChildren();for(const p of game.players){const el=document.createElement('article');el.className=`player ${p.id===game.turn?'current':''} ${p.alive?'':'dead'}`;const role=p.id===0||p.role==='lord'||!p.alive||game.winner?roles[p.role]:'身份未知';el.innerHTML=`<small>${p.id+1}号位 · ${p.id===0?'你':'电脑'}</small><h3>${game.name(p)}</h3><span>${role}</span><p class="hp">${'♥'.repeat(Math.max(0,p.hp))} ${p.hp}/${p.maxHp}</p><p>手牌 ${p.hand.length} · ${p.alive?p.general.skill:'已阵亡'}</p>`;$('players').append(el);}
  $('hand').replaceChildren();$('count').textContent=`${me.hand.length} 张`;
  for(const c of me.hand){const b=button('',()=>{selected.has(c.uid)?selected.delete(c.uid):selected.add(c.uid);},$('hand'));b.className=`card ${c.red?'red':''} ${selected.has(c.uid)?'selected':''}`;b.innerHTML=`<span>${c.suit} ${c.rank}</span><strong>${cards[c.type][0]}</strong><small>${cards[c.type][1]}</small>`;b.setAttribute('aria-pressed',selected.has(c.uid));b.disabled=!!game.winner||game.turn!==0||game.phase!=='play'||!!game.pending;}
  $('choices').replaceChildren();$('controls').replaceChildren();$('hint').textContent=missions[me.role];
  if(game.winner){$('prompt').textContent='本局结束';$('result').hidden=false;const won=game.winner==='lord'?['lord','loyalist'].includes(me.role):game.winner===me.role;$('result').innerHTML=`<h2>${won?'你获胜了':'本局失利'}</h2><p>${game.winner==='lord'?'主公与忠臣':roles[game.winner]}获胜。${game.players.map(p=>`${game.name(p)}：${roles[p.role]}`).join('；')}</p>`;button('再来一局',reset,$('result'));}
  else{$('result').hidden=true;if(game.pending){$('prompt').textContent=game.pending.player===0?game.pending.text:`等待${game.name(game.players[game.pending.player])}响应…`;if(game.pending.player===0)for(const o of game.pending.options)button(o.label,()=>game.answer(o.id),$('choices'));}
  else if(game.turn===0&&game.phase==='play'){$('prompt').textContent='轮到你了';$('hint').textContent='选择一张手牌，再选择出牌方式；仁德与制衡支持多选。';const ids=[...selected];if(ids.length===1)for(const a of game.options().filter(a=>a.uid===ids[0]))button(`${cards[a.type][0]}${a.target!==0?' → '+game.name(game.players[a.target]):''}`,()=>{game.play(a);selected.clear();},$('choices'));if(ids.length&&game.is(me,'sunquan')&&!me.used)button(`制衡 ${ids.length} 张`,()=>{game.skill(ids);selected.clear();},$('choices'));if(ids.length&&game.is(me,'liubei'))for(const q of game.players.filter(p=>p.id!==0&&p.alive))button(`仁德 → ${game.name(q)}`,()=>{game.skill(ids,q.id);selected.clear();},$('choices'));button('取消选择',()=>selected.clear(),$('controls'));button('结束出牌',()=>{selected.clear();game.end();},$('controls'));}
  else $('prompt').textContent=me.alive?`${game.name(current)}行动中…`:'你已阵亡，正在观战…';}
  $('log').replaceChildren();for(const msg of [...game.logs].reverse()){const li=document.createElement('li');li.textContent=msg;$('log').append(li);}
}
function schedule(){clearTimeout(timer);if(game.phase==='identity'||game.winner)return;if(game.pending?.player===0)return;if(!game.pending&&game.phase==='play'&&game.turn===0)return;const ticket=epoch;timer=setTimeout(()=>{if(ticket!==epoch)return;act(()=>game.aiStep());},550);}
$('restart').onclick=()=>{if(game.phase==='identity'||game.winner||confirm('结束当前对局并重新发身份？'))reset();};reset();
