(function(root){
  'use strict';
  const generals = [
    ['liubei','刘备','蜀',4,'仁德','交给其他角色手牌；本回合累计给出两张时回复1点体力。'],
    ['guanyu','关羽','蜀',4,'武圣','红色手牌可当杀使用或打出。'],
    ['zhangfei','张飞','蜀',4,'咆哮','出牌阶段使用杀没有次数限制。'],
    ['caocao','曹操','魏',4,'奸雄','受伤后可获得造成伤害的牌。'],
    ['xiahoudun','夏侯惇','魏',4,'刚烈','受伤后可判定：非红桃，来源弃两张手牌或受1点伤害。'],
    ['sunquan','孙权','吴',4,'制衡','出牌阶段限一次：弃任意张手牌，摸等量牌。'],
    ['zhouyu','周瑜','吴',3,'英姿','摸牌阶段额外摸一张牌。'],
    ['huatuo','华佗','群',3,'急救','回合外可将红色手牌当桃救援濒死角色。']
  ].map(([id,name,kingdom,hp,skill,text])=>({id,name,kingdom,hp,skill,text}));
  const roles={lord:'主公',loyalist:'忠臣',rebel:'反贼',renegade:'内奸'};
  const cards={slash:['杀','距离1以内；每回合限一次，对方可出闪。'],dodge:['闪','响应杀或万箭齐发。'],peach:['桃','回复1点体力，或救援濒死角色。'],duel:['决斗','对方先出杀，双方轮流响应。'],dismantle:['过河拆桥','随机弃置其他角色一张手牌。'],steal:['顺手牵羊','随机获得距离1的其他角色一张手牌。'],draw2:['无中生有','摸两张牌。'],barbarians:['南蛮入侵','其他角色依次出杀，否则受1点伤害。'],arrows:['万箭齐发','其他角色依次出闪，否则受1点伤害。']};
  class Game {
    constructor(random=Math.random){this.random=random;this.phase='identity';this.logs=[];this.deck=[];this.discard=[];this.table=[];this.turn=0;this.round=0;this.winner=null;this.pending=null;this.task=null;this.reputation=[0,0,0,0];this.players=this.shuffle(Object.keys(roles)).map((role,id)=>({id,role,general:null,hp:0,maxHp:0,alive:true,hand:[]}));this.log('身份已发放。请选择武将。');}
    shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(this.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
    log(s){this.logs.push(s);if(this.logs.length>160)this.logs.shift();}
    name(p){return p.general?.name||`${p.id+1}号位`;}
    start(id){if(this.phase!=='identity')throw Error('本局已开始');const g=generals.find(g=>g.id===id);if(!g)throw Error('请选择武将');const other=this.shuffle(generals.filter(x=>x!==g));this.players.forEach((p,i)=>{p.general=i?other.pop():g;p.hp=p.maxHp=p.general.hp;});let uid=0;for(const [type,n]of Object.entries({slash:24,dodge:15,peach:8,duel:3,dismantle:4,steal:4,draw2:4,barbarians:2,arrows:1})){for(let i=0;i<n;i++){const suit=['♥','♦','♠','♣'][uid%4];this.deck.push({uid:uid++,type,suit,red:suit==='♥'||suit==='♦',rank:1+(i%13)});}}this.shuffle(this.deck);this.players.forEach(p=>this.draw(p,4));this.turn=this.players.findIndex(p=>p.role==='lord');this.phase='ready';this.log('各摸4张起手牌，主公先行动；四人局主公不加体力。');}
    draw(p,n){if(!p.alive)return;for(let i=0;i<n;i++){if(!this.deck.length){this.deck=this.shuffle(this.discard.splice(0));if(this.deck.length)this.log('弃牌堆重新洗牌。');}if(!this.deck.length)break;p.hand.push(this.deck.pop());}}
    remove(p,uid){const i=p.hand.findIndex(c=>c.uid===uid);if(i<0)throw Error('手牌不存在');return p.hand.splice(i,1)[0];}
    toss(p,uid){const c=this.remove(p,uid);this.discard.push(c);return c;}
    distance(a,b){const alive=this.players.filter(p=>p.alive);const d=Math.abs(alive.indexOf(a)-alive.indexOf(b));return Math.min(d,alive.length-d);}
    is(p,id){return p.general?.id===id;}
    responseCards(p,type){return p.hand.filter(c=>c.type===type||(type==='slash'&&this.is(p,'guanyu')&&c.red)||(type==='peach'&&this.is(p,'huatuo')&&p.id!==this.turn&&c.red));}
    *ask(p,text,options,optional=true){if(!options.length)return null;return yield {player:p.id,text,options:[...options,...(optional?[{id:'pass',label:'放弃'}]:[])]};}
    *respond(p,type,text){const uid=yield* this.ask(p,text,this.responseCards(p,type).map(c=>({id:c.uid,label:`${c.suit}${c.rank} ${cards[c.type][0]} → ${cards[type][0]}`})));if(uid===null||uid==='pass')return false;this.toss(p,uid);this.log(`${this.name(p)}打出${cards[type][0]}。`);return true;}
    checkWinner(){const alive=this.players.filter(p=>p.alive);if(!alive.some(p=>p.role==='lord'))this.winner=alive.length===1&&alive[0].role==='renegade'?'renegade':'rebel';else if(!alive.some(p=>p.role==='rebel'||p.role==='renegade'))this.winner='lord';if(this.winner){this.phase='over';this.log(`${this.winner==='lord'?'主公与忠臣':roles[this.winner]}获胜。`);}return !!this.winner;}
    *dying(p,source){while(p.hp<=0&&p.alive){let saved=false;for(let i=0;i<4;i++){const helper=this.players[(this.turn+i)%4];if(!helper.alive)continue;if(yield* this.respond(helper,'peach',`${this.name(p)}濒死（${p.hp}体力），是否出桃救援？`)){p.hp++;saved=true;if(p.hp>0)break;}}if(!saved){p.alive=false;this.discard.push(...p.hand.splice(0));this.log(`${this.name(p)}阵亡，身份是${roles[p.role]}。`);if(this.checkWinner())return;if(source?.alive){if(p.role==='rebel'){this.draw(source,3);this.log('击杀反贼，奖励3张牌。');}if(p.role==='loyalist'&&source.role==='lord'){this.discard.push(...source.hand.splice(0));this.log('主公误杀忠臣，弃置全部手牌。');}}}}}
    *damage(p,source,card){if(!p.alive||this.winner)return;p.hp--;this.log(`${this.name(p)}受到1点伤害。`);if(p.hp<=0)yield* this.dying(p,source);if(!p.alive||this.winner)return;
      if(this.is(p,'caocao')&&card&&this.table.includes(card)){const a=yield* this.ask(p,'是否发动奸雄，获得伤害牌？',[{id:'yes',label:'发动奸雄'}]);if(a==='yes'){this.table.splice(this.table.indexOf(card),1);p.hand.push(card);}}
      if(this.is(p,'xiahoudun')&&source?.alive){const a=yield* this.ask(p,'是否发动刚烈？',[{id:'yes',label:'发动刚烈'}]);if(a!=='yes')return;if(!this.deck.length)this.deck=this.shuffle(this.discard.splice(0));const judge=this.deck.pop();if(!judge)return;this.discard.push(judge);this.log(`刚烈判定：${judge.suit}${judge.rank}。`);if(judge.suit!=='♥'){let choice='hurt';if(source.hand.length>=2)choice=yield* this.ask(source,'刚烈：弃两张手牌或受1点伤害。',[{id:'discard',label:'弃两张手牌'},{id:'hurt',label:'受到伤害'}],false);if(choice==='discard'){for(let i=0;i<2;i++){const uid=yield* this.ask(source,'选择刚烈弃牌',source.hand.map(c=>({id:c.uid,label:cards[c.type][0]})),false);this.toss(source,uid);}}else yield* this.damage(source,p,null);}}
    }
    run(generator){if(this.task)throw Error('请先完成当前响应');this.task=generator;this.advance();}
    advance(value){const next=this.task.next(value);this.pending=next.done?null:next.value;if(next.done)this.task=null;}
    answer(id){if(!this.pending||!this.pending.options.some(o=>o.id===id))throw Error('无效响应');this.advance(id);}
    begin(){if(this.phase!=='ready'||this.task||this.winner)throw Error('不能开始回合');const p=this.players[this.turn];p.slashes=0;p.used=false;p.given=0;this.round++;this.draw(p,this.is(p,'zhouyu')?3:2);this.phase='play';this.log(`第${this.round}回合：${this.name(p)}摸牌，进入出牌阶段。`);}
    targets(p,type){return this.players.filter(q=>q.alive&&q!==p&&(!(type==='slash'||type==='steal')||this.distance(p,q)<=1)&&(!(type==='steal'||type==='dismantle')||q.hand.length));}
    options(p=this.players[this.turn]){if(this.phase!=='play'||p.id!==this.turn||this.task||!p.alive)return [];const result=[];for(const c of p.hand){const types=[c.type];if(this.is(p,'guanyu')&&c.red&&c.type!=='slash')types.push('slash');for(const type of types){if(type==='dodge'||(type==='peach'&&p.hp>=p.maxHp)||(type==='slash'&&p.slashes>=1&&!this.is(p,'zhangfei')))continue;if(['slash','duel','steal','dismantle'].includes(type)){for(const q of this.targets(p,type))result.push({uid:c.uid,type,target:q.id});}else result.push({uid:c.uid,type,target:p.id});}}return result;}
    play(action){if(!this.options().some(a=>a.uid===action.uid&&a.type===action.type&&a.target===action.target))throw Error('这张牌当前无法如此使用');this.run(this.resolve(action));}
    *resolve({uid,type,target}){const p=this.players[this.turn],q=this.players[target],c=this.remove(p,uid);this.table.push(c);this.log(`${this.name(p)}使用${cards[type][0]}${q!==p?' → '+this.name(q):''}。`);if(q!==p&&q.role==='lord')this.reputation[p.id]--;if(type==='slash'){p.slashes++;if(!(yield* this.respond(q,'dodge',`${this.name(p)}对你使用杀，是否出闪？`)))yield* this.damage(q,p,c);}else if(type==='peach')p.hp=Math.min(p.maxHp,p.hp+1);else if(type==='draw2')this.draw(p,2);else if(type==='duel'){let defender=q,attacker=p;while(defender.alive&&attacker.alive&&!this.winner){if(!(yield* this.respond(defender,'slash',`与${this.name(attacker)}决斗，请出杀。`))){yield* this.damage(defender,attacker,c);break;}[defender,attacker]=[attacker,defender];}}else if(type==='dismantle'||type==='steal'){const taken=this.remove(q,q.hand[Math.floor(this.random()*q.hand.length)].uid);if(type==='steal')p.hand.push(taken);else this.discard.push(taken);}else{for(let i=1;i<4;i++){const other=this.players[(p.id+i)%4];if(!other.alive||this.winner)continue;if(!(yield* this.respond(other,type==='arrows'?'dodge':'slash',`${cards[type][0]}：请响应。`)))yield* this.damage(other,p,c);}}
      if(this.table.includes(c)){this.table.splice(this.table.indexOf(c),1);this.discard.push(c);}if(!p.alive&&!this.winner)this.nextTurn();
    }
    skill(uids,target){const p=this.players[this.turn];if(this.phase!=='play'||this.task||!p.alive)throw Error('现在不能发动技能');if(!uids.length||new Set(uids).size!==uids.length||uids.some(id=>!p.hand.some(c=>c.uid===id)))throw Error('请选择有效手牌');if(this.is(p,'sunquan')&&!p.used){p.used=true;uids.forEach(id=>this.toss(p,id));this.draw(p,uids.length);this.log('孙权发动制衡。');}else if(this.is(p,'liubei')){const q=this.players[target];if(!q?.alive||q===p)throw Error('请选择其他存活角色');uids.forEach(id=>q.hand.push(this.remove(p,id)));if(p.given<2&&p.given+uids.length>=2)p.hp=Math.min(p.maxHp,p.hp+1);p.given+=uids.length;this.log(`刘备发动仁德，交给${this.name(q)}${uids.length}张牌。`);}else throw Error('技能不可用');}
    end(){if(this.phase!=='play'||this.task||this.winner)throw Error('不能结束回合');this.run(this.discardPhase());}
    *discardPhase(){this.phase='discard';const p=this.players[this.turn];while(p.alive&&p.hand.length>Math.max(0,p.hp)){const uid=yield* this.ask(p,`弃牌阶段：还需弃${p.hand.length-Math.max(0,p.hp)}张。`,p.hand.map(c=>({id:c.uid,label:`${c.suit}${c.rank} ${cards[c.type][0]}`})),false);this.toss(p,uid);}this.nextTurn();}
    nextTurn(){if(this.winner)return;do{this.turn=(this.turn+1)%4;}while(!this.players[this.turn].alive);this.phase='ready';}
    // AI only uses its own identity and public information; it cannot inspect hidden roles.
    enemyScore(p,q){if(q===p)return -99;if(p.role==='rebel')return q.role==='lord'?10:2;if(p.role==='loyalist')return q.role==='lord'?-10:4-this.reputation[q.id];if(p.role==='lord')return 3-this.reputation[q.id];return q.role==='lord'?(this.players.filter(x=>x.alive).length===2?10:-5):5;}
    value(c){return {peach:9,dodge:7,slash:5,draw2:8}[c.type]||4;}
    aiStep(){if(this.winner)return;if(this.pending){const req=this.pending,p=this.players[req.player];let pick=req.options[0];if(req.text.includes('濒死')){const dying=this.players.find(x=>x.alive&&x.hp<=0);if(dying&&dying!==p&&this.enemyScore(p,dying)>0)pick=req.options.find(x=>x.id==='pass')||pick;}else if(req.text.includes('弃')){const actual=req.options.filter(o=>p.hand.some(c=>c.uid===o.id));if(actual.length)pick=actual.sort((a,b)=>this.value(p.hand.find(c=>c.uid===a.id))-this.value(p.hand.find(c=>c.uid===b.id)))[0];}this.answer(pick.id);return;}if(this.phase==='ready'){this.begin();return;}const p=this.players[this.turn];if(this.is(p,'sunquan')&&!p.used&&p.hand.length){const weak=p.hand.filter(c=>this.value(c)<6).map(c=>c.uid);if(weak.length){this.skill(weak);return;}}const actions=this.options().map(a=>({...a,score:a.type==='peach'?30:a.type==='draw2'?20:['arrows','barbarians'].includes(a.type)?1:this.enemyScore(p,this.players[a.target])})).filter(a=>a.score>0).sort((a,b)=>b.score-a.score);if(actions.length)this.play(actions[0]);else this.end();}
  }
  const api={Game,generals,roles,cards};if(typeof module!=='undefined')module.exports=api;else root.SGS=api;
})(typeof globalThis!=='undefined'?globalThis:this);
