const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Game,generals,deckSize}=require('../engine.js');
function seeded(seed){return ()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);}
function game(){const g=new Game(seeded(42));g.start('zhangfei');g.players.forEach((p,i)=>{p.general=generals[i];p.role=['lord','loyalist','rebel','renegade'][i];});g.turn=0;g.begin();return g;}
let uid=10000;function card(type,red=false){return {uid:uid++,type,red,suit:red?'♥':'♠',rank:1};}
function clear(g){g.players.forEach(p=>{g.discard.push(...p.hand.splice(0));});}
function settle(g,choose=req=>req.options.find(o=>o.id==='pass')?.id??req.options[0].id){let n=0;while(g.pending){assert.ok(n++<100);g.answer(choose(g.pending));}}
test('identity precedes selection; four distinct roles and generals; full deck',()=>{const g=new Game(seeded(1));assert.equal(g.phase,'identity');assert.equal(new Set(g.players.map(p=>p.role)).size,4);g.start('liubei');assert.equal(new Set(g.players.map(p=>p.general.id)).size,4);assert.ok(g.players.every(p=>p.hand.length===4));assert.equal(g.deck.length,deckSize-16);assert.equal(g.players[g.turn].role,'lord');assert.ok(g.players.every(p=>p.hp===p.general.hp));assert.throws(()=>g.start('guanyu'));});
test('slash asks human, dodge avoids damage; once per turn; invalid actions do not consume',()=>{const g=game();clear(g);g.players[0].hand=[card('slash'),card('slash')];g.players[1].hand=[card('dodge')];const hp=g.players[1].hp;assert.throws(()=>g.play({uid:g.players[0].hand[0].uid,type:'slash',target:2}));g.play({uid:g.players[0].hand[0].uid,type:'slash',target:1});assert.equal(g.pending.player,1);g.answer(g.pending.options[0].id);assert.equal(g.players[1].hp,hp);assert.equal(g.options().filter(a=>a.type==='slash').length,0);});
test('live-seat distance collapses after death',()=>{const g=game();assert.equal(g.distance(g.players[0],g.players[2]),2);g.players[1].alive=false;assert.equal(g.distance(g.players[0],g.players[2]),1);});
test('peach rescue prevents death, human can decline',()=>{const g=game();clear(g);const p=g.players[1];p.hp=1;g.players[0].hand=[card('peach')];g.run(g.damage(p,g.players[2],null));assert.equal(g.pending.player,0);g.answer(g.pending.options[0].id);assert.equal(p.hp,1);assert.equal(p.alive,true);});
test('loyalist kill penalty and rebel reward',()=>{for(const target of [1,2]){const g=game();clear(g);g.players[target].hp=1;g.players[0].hand=[card('slash')];g.run(g.damage(g.players[target],g.players[0],null));settle(g);assert.equal(g.players[target].alive,false);assert.equal(g.players[0].hand.length,target===1?0:4);}});
test('all victory branches including dead rebel and simultaneous lord loss',()=>{const scenarios=[[[true,true,false,false],'lord'],[[false,true,false,true],'rebel'],[[false,false,false,true],'renegade'],[[false,false,false,false],'rebel']];for(const [living,winner]of scenarios){const g=game();g.players.forEach((p,i)=>p.alive=living[i]);assert.equal(g.checkWinner(),true);assert.equal(g.winner,winner);}});
test('duel alternates responses and damages first failure',()=>{const g=game();clear(g);g.players[0].hand=[card('duel')];g.players[1].hand=[card('slash')];g.play({uid:g.players[0].hand[0].uid,type:'duel',target:1});g.answer(g.pending.options[0].id);settle(g);assert.equal(g.players[0].hp,3);assert.equal(g.task,null);});
test('discard requires exact excess, then next living player',()=>{const g=game();g.players[0].hp=2;const count=g.players[0].hand.length;g.end();let n=0;while(g.pending){g.answer(g.pending.options[0].id);n++;}assert.equal(n,count-2);assert.equal(g.players[0].hand.length,2);assert.equal(g.turn,1);assert.equal(g.phase,'ready');});
test('red conversion for Guan Yu and Hua Tuo only off turn',()=>{const g=game(),p=g.players[0];p.general=generals.find(x=>x.id==='guanyu');p.hand=[card('dodge',true)];assert.equal(g.responseCards(p,'slash').length,1);p.general=generals.find(x=>x.id==='huatuo');assert.equal(g.responseCards(p,'peach').length,0);g.turn=1;assert.equal(g.responseCards(p,'peach').length,1);});
test('Rende heals once after two gifts; Zhiheng once; Yingzi draws three; Paoxiao unlimited',()=>{const g=game(),p=g.players[0];p.hp=2;g.skill([p.hand[0].uid],1);assert.equal(p.hp,2);g.skill([p.hand[0].uid],1);assert.equal(p.hp,3);g.skill([p.hand[0].uid],1);assert.equal(p.hp,3);p.general=generals.find(x=>x.id==='sunquan');const n=p.hand.length;g.skill(p.hand.slice(0,2).map(c=>c.uid));assert.equal(p.hand.length,n);assert.throws(()=>g.skill([p.hand[0].uid]));p.general=generals.find(x=>x.id==='zhouyu');g.phase='ready';const before=p.hand.length;g.begin();assert.equal(p.hand.length,before+3);p.general=generals.find(x=>x.id==='zhangfei');p.hand=[card('slash')];p.slashes=3;assert.ok(g.options().some(a=>a.type==='slash'));});
test('Jianxiong obtains damage card only once',()=>{const g=game();clear(g);g.players[1].general=generals.find(x=>x.id==='caocao');const c=card('slash');g.players[0].hand=[c];g.play({uid:c.uid,type:'slash',target:1});assert.equal(g.pending.options[0].id,'yes');g.answer('yes');assert.ok(g.players[1].hand.includes(c));assert.ok(!g.discard.includes(c));assert.equal(g.table.length,0);});
test('Ganglie judgment, two-card discard, damage alternative',()=>{const g=game();clear(g);g.players[1].general=generals.find(x=>x.id==='xiahoudun');g.deck.push(card('slash'));g.players[0].hand=[card('slash'),card('dodge')];g.run(g.damage(g.players[1],g.players[0],null));g.answer('yes');g.answer('discard');settle(g,req=>req.options[0].id);assert.equal(g.players[0].hand.length,0);assert.equal(g.players[0].hp,4);});
test('deck recycles and keeps card ownership unique over 150 full AI games',()=>{const winners=new Set();for(let seed=1;seed<=150;seed++){const g=new Game(seeded(seed));g.start(generals[seed%8].id);let steps=0;while(!g.winner&&steps++<12000){g.aiStep();const all=[...g.deck,...g.discard,...g.table,...g.players.flatMap(p=>g.owned(p))];assert.equal(all.length,deckSize,`seed ${seed} step ${steps}`);assert.equal(new Set(all.map(c=>c.uid)).size,deckSize);assert.ok(g.players.filter(p=>!p.alive).every(p=>!g.owned(p).length));}assert.ok(g.winner,`seed ${seed} did not terminate`);winners.add(g.winner);}assert.ok(winners.size>=2);});
