const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Game,generals}=require('../engine.js');
let seq=1000;
const card=(type,suit='♠')=>({uid:seq++,type,suit,red:['♥','♦'].includes(suit),rank:1});
function setup(){const g=new Game(()=>0.4);g.start('zhangfei');g.players.forEach((p,i)=>{g.discard.push(...p.hand.splice(0));p.general=generals.find(x=>x.id==='zhangfei');p.role=['lord','loyalist','rebel','renegade'][i];p.hp=p.maxHp=4;});g.turn=0;g.begin();g.discard.push(...g.players[0].hand.splice(0));return g;}
function hero(g,i,name){g.players[i].general=generals.find(x=>x.id===name);}
function pass(g){let n=0;while(g.pending){assert.ok(n++<80);g.answer(g.pending.options.find(o=>o.id==='pass')?.id??g.pending.options[0].id);}}
function use(g,type,target=1,suit='♠'){const c=card(type,suit);g.players[g.turn].hand.push(c);g.play({uid:c.uid,type,target});return c;}
test('standard secondary and lord skill names are present',()=>{for(const name of ['激将','护驾','救援','反间','青囊'])assert.ok(generals.some(g=>g.skill.includes(name)));});
test('Jijiang actively obtains allied Shu slash; consumes one slash use',()=>{const g=setup();hero(g,0,'liubei');hero(g,1,'guanyu');const c=card('peach','♥');g.players[1].hand=[c];g.play({uid:'jijiang',type:'slash',target:3});assert.equal(g.pending.player,1);g.answer(c.uid);assert.equal(g.players[3].hp,3);assert.equal(g.players[0].slashes,1);assert.ok(g.discard.includes(c));assert.equal(g.table.length,0);});
test('Jijiang failed active request does not spend slash and cannot repeat in same phase',()=>{const g=setup();hero(g,0,'liubei');g.play({uid:'jijiang',type:'slash',target:1});assert.equal(g.players[0].slashes,0);assert.equal(g.pending,null);assert.ok(!g.options().some(a=>a.uid==='jijiang'));});
test('non-lord cannot activate Jijiang or Hujia',()=>{const g=setup();hero(g,1,'liubei');g.turn=1;g.players[1].slashes=0;assert.ok(!g.options().some(a=>a.uid==='jijiang'));hero(g,1,'caocao');g.run(g.respond(g.players[1],'dodge','test'));assert.equal(g.pending,null);});
test('Hujia lets a Wei helper provide dodge',()=>{const g=setup();hero(g,0,'caocao');hero(g,1,'xiahoudun');const c=card('dodge');g.players[1].hand=[c];g.turn=3;g.players[3].slashes=0;use(g,'slash',0);g.answer('lord');assert.equal(g.pending.player,1);g.answer(c.uid);assert.equal(g.players[0].hp,4);assert.equal(g.task,null);});
test('failed Hujia still permits own dodge',()=>{const g=setup();hero(g,0,'caocao');const c=card('dodge');g.players[0].hand=[c];g.turn=3;g.players[3].slashes=0;use(g,'slash',0);g.answer('lord');assert.ok(g.pending.options.some(o=>o.id===c.uid));g.answer(c.uid);assert.equal(g.players[0].hp,4);});
test('Jijiang works during duel response and uses helper card',()=>{const g=setup();hero(g,0,'liubei');hero(g,2,'guanyu');const c=card('slash');g.players[2].hand=[c];g.turn=1;use(g,'duel',0);g.answer('lord');assert.equal(g.pending.player,2);g.answer(c.uid);assert.equal(g.players[1].hp,3);});
test('Jiuyuan heals an extra point only for lord Sun Quan with another Wu peach',()=>{for(const [role,kingdom,hp]of [['lord','zhouyu',2],['loyalist','zhouyu',1],['lord','guanyu',1]]){const g=setup();hero(g,0,'sunquan');g.players[0].role=role;hero(g,1,kingdom);g.players[0].hp=1;const c=card('peach');g.players[1].hand=[c];g.run(g.damage(g.players[0],g.players[3],null));g.answer(c.uid);assert.equal(g.players[0].hp,hp);}});
test('Qingnang validates wounded target, hand cost and once per phase',()=>{const g=setup();hero(g,0,'huatuo');const c=card('slash');g.players[0].hand=[c];assert.throws(()=>g.secondary(1,c.uid));assert.equal(g.players[0].hand.length,1);g.players[1].hp=2;g.secondary(1,c.uid);assert.equal(g.players[1].hp,3);assert.ok(g.discard.includes(c));assert.throws(()=>g.secondary(1,c.uid));});
test('Fanjian transfers revealed card, wrong guess damages; cannot be nullified',()=>{for(const suit of ['♥','♠']){const g=setup();hero(g,0,'zhouyu');const c=card('slash','♥');g.players[0].hand=[c];g.players[1].hand=[card('nullify')];g.secondary(1);assert.equal(g.pending.kind,'fanjian');g.answer(suit);assert.equal(g.players[1].hp,suit==='♥'?4:3);assert.ok(g.players[1].hand.includes(c));assert.throws(()=>g.secondary(2));assert.equal(g.pending,null);}});
test('equipment replaces same slot but preserves other slots; equipment not counted for discard',()=>{const g=setup(),p=g.players[0];const first=use(g,'crossbow',0);use(g,'bagua',0);use(g,'qinggang',0);assert.equal(p.equip.length,2);assert.ok(g.discard.includes(first));p.hp=1;g.end();assert.equal(g.pending,null);assert.equal(p.equip.length,2);});
test('mount distances and weapon range; consuming a mount or weapon loses its benefits',()=>{const g=setup(),p=g.players[0];hero(g,0,'guanyu');assert.equal(g.distance(p,g.players[2]),2);const horse=card('chitu','♥');p.equip=[horse];assert.equal(g.distance(p,g.players[2]),1);assert.ok(!g.options().some(a=>a.uid===horse.uid&&a.target===2));p.equip=[card('qinggang','♥')];assert.equal(g.range(p),2);assert.ok(!g.options().some(a=>a.target===2));p.hand=[card('slash')];assert.ok(g.options().some(a=>a.target===2));g.players[1].equip=[card('jueying')];assert.equal(g.distance(p,g.players[1]),2);});
test('crossbow permits multiple slashes but cannot finance its own extra slash',()=>{const g=setup(),p=g.players[0];hero(g,0,'guanyu');p.slashes=2;const bow=card('crossbow','♥');p.equip=[bow];p.hand=[card('slash')];assert.ok(g.options().some(a=>a.uid===p.hand[0].uid));assert.ok(!g.options().some(a=>a.uid===bow.uid));});
test('Renwang blocks black slash; Qinggang bypasses it; red slash remains effective',()=>{for(const [weapon,suit,hp]of [[null,'♠',4],['qinggang','♠',3],[null,'♥',3]]){const g=setup();g.players[1].equip=[card('renwang')];if(weapon)g.players[0].equip=[card(weapon)];use(g,'slash',1,suit);assert.equal(g.players[1].hp,hp);}});
test('Bagua uses real judgment; failed judgment permits hand dodge; Qinggang prevents armor prompt',()=>{for(const red of [true,false]){const g=setup();g.players[1].equip=[card('bagua')];const d=card('dodge');g.players[1].hand=[d];const j=card('slash',red?'♥':'♠');g.deck.push(j);use(g,'slash');g.answer('bagua');if(!red)g.answer(d.uid);assert.equal(g.players[1].hp,4);assert.ok(g.discard.includes(j));}const g=setup();g.players[0].equip=[card('qinggang')];g.players[1].equip=[card('bagua')];use(g,'slash');assert.equal(g.pending,null);assert.equal(g.players[1].hp,3);});
test('Dismantle and Steal can select a visible equipment, leaving hidden hand alone',()=>{for(const type of ['dismantle','steal']){const g=setup(),q=g.players[1],c=card('bagua');q.equip=[c];q.hand=[card('peach')];use(g,type);assert.equal(g.pending.kind,'zone');g.answer(c.uid);assert.equal(q.equip.length,0);assert.equal(q.hand.length,1);assert.ok((type==='steal'?g.players[0].hand:g.discard).includes(c));}});
test('Zhiheng and Wusheng can consume equipped cards; Rende cannot',()=>{const g=setup(),p=g.players[0],c=card('bagua','♥');p.equip=[c];hero(g,0,'liubei');assert.throws(()=>g.skill([c.uid],1));hero(g,0,'sunquan');g.skill([c.uid]);assert.equal(p.equip.length,0);assert.equal(p.hand.length,1);p.equip=[card('bagua','♥')];hero(g,0,'guanyu');assert.ok(g.responseCards(p,'slash').includes(p.equip[0]));hero(g,0,'huatuo');g.turn=1;assert.ok(g.responseCards(p,'peach').includes(p.equip[0]));});
test('death and loyalist penalty discard equipment',()=>{const g=setup();g.players[0].equip=[card('qinggang')];g.players[1].equip=[card('bagua')];g.players[1].hp=1;g.run(g.damage(g.players[1],g.players[0],null));assert.equal(g.players[1].equip.length,0);assert.equal(g.players[0].equip.length,0);});
test('one nullification cancels draw2 and three counters keep it canceled',()=>{for(const count of [1,3]){const g=setup(),p=g.players[0];g.players[1].hand=Array.from({length:count},()=>card('nullify'));const before=g.deck.length;use(g,'draw2',0);while(g.pending)g.answer(g.pending.options[0].id);assert.equal(g.deck.length,before);assert.equal(p.hand.length,0);assert.equal(g.table.length,0);}});
test('two nullifications restore draw2; passing permits original effect',()=>{for(const count of [0,2]){const g=setup(),p=g.players[0];g.players[1].hand=[card('nullify'),card('nullify')];use(g,'draw2',0);let used=0;while(g.pending){g.answer(used++<count?g.pending.options[0].id:'pass');}assert.equal(p.hand.length,2);assert.equal(g.table.length,0);}});
test('AOE nullification protects one target only; next target receives a fresh window',()=>{const g=setup();g.players[1].hand=[card('nullify')];use(g,'arrows',0);assert.equal(g.pending.target,1);g.answer(g.pending.options[0].id);assert.equal(g.players[1].hp,4);assert.equal(g.players[2].hp,3);assert.equal(g.players[3].hp,3);});
test('nullify cannot be played proactively or used against slash and equipment',()=>{const g=setup();g.players[0].hand=[card('nullify')];g.players[1].hand=[card('nullify')];assert.equal(g.options().length,0);use(g,'slash');assert.equal(g.pending,null);use(g,'bagua',0);assert.equal(g.pending,null);});
